# Generated by Django 2.2.4 on 2019-08-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitch_User',
            fields=[
                ('twitch_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
                ('twitch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Twitch_User')),
            ],
        ),
    ]
